version: '2'
services:
    bills-app:
        image: bills
        external_links:
            - bills-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/bills
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bills-postgresql:
        extends:
            file: postgresql.yml
            service: bills-postgresql
